module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/test'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/index.ts',
    '!src/cli.ts',
    '!src/reporter.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  // Example configuration for using jest-swag reporter
  // Uncomment the lines below to generate documentation during tests
  // reporters: [
  //   'default',
  //   ['<rootDir>/src/reporter/jest-reporter.ts', {
  //     title: 'jest-swag API Documentation',
  //     version: '1.0.0',
  //     description: 'Generated by jest-swag example',
  //     outputPath: './docs/openapi.json',
  //     servers: [
  //       { url: 'http://localhost:3000', description: 'Development server' }
  //     ]
  //   }]
  // ]
};
